### ISSUE TITLE
Dists page with cluster and ipfs-pack 0.3.0

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/infrastructure#258]
https://ipfs.io/ipfs/Qma5SEusRzT5AQstz2TCqE68yhZBQVf6TUPrBEDt34GkXj/

cc @hsanjuan Its Happening!

**Comment by lgierth** [comment]
done

**Comment by hsanjuan** [comment]
@lgierth I still don't see the new page in dist.ipfs.io... isn't it taking too long?

**Comment by lgierth** [comment]
Okay should be up now -- not sure what I did wrong there
